dbt_project:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: gcp-first-project-493504
      dataset: dbt_subscription
      threads: 4
      keyfile: /opt/airflow/dbt_project/gcp_key.json
      location: US