version: 2

seeds:
  - name: raw_subscription
    description: "Raw historical ingest of user subscription changes"
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: user_id
        data_tests:
          - not_null
      - name: status
        data_tests:
          - accepted_values:
              arguments:
                values: ['active', 'expired', 'cancelled', 'upgraded']